// src/lib/components/hat-selector.svelte
<script lang="ts">
	import type { Hat } from '$lib';
	import { Button } from '$lib/components/ui/button';
	import { Card } from '$lib/components/ui/card';

	export let selectedHat: Hat | null = null;
	export let onSelect: () => void;
	export let hatsCount: number = 0;
</script>

<div class="h-full">
	<h2 class="mb-4 text-xl font-semibold">Today's Hat</h2>

	<Card class="flex flex-col items-center p-6">
		{#if selectedHat}
			<div class="mb-4 h-64 w-64 overflow-hidden rounded-lg bg-gray-100">
				{#if selectedHat.imageUrl}
					<img
						src={selectedHat.imageUrl}
						alt={selectedHat.name}
						class="h-full w-full object-cover"
					/>
				{:else}
					<div class="flex h-full w-full items-center justify-center text-gray-400">No image</div>
				{/if}
			</div>

			<h3 class="mb-2 text-2xl font-bold">{selectedHat.name}</h3>
		{:else}
			<div
				class="mb-4 flex h-64 w-64 items-center justify-center rounded-lg bg-gray-100 text-gray-400"
			>
				No hat selected
			</div>

			<p class="mb-6 text-center">
				{#if hatsCount === 0}
					Add some hats to the collection
				{/if}
			</p>
		{/if}

		<Button disabled={hatsCount === 0} onclick={onSelect} class="px-8">Pick a hat</Button>
	</Card>
</div>

// components/HatSelector.tsx
import { View, Text, StyleSheet, TouchableOpacity, Image } from 'react-native';
import type { Hat } from '@/types';

interface HatSelectorProps {
  selectedHat: Hat | null;
  onSelect: () => void;
  hatsCount: number;
}

export default function HatSelector({ selectedHat, onSelect, hatsCount }: HatSelectorProps) {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Today&apos;s Hat</Text>
      
      <View style={styles.card}>
        {selectedHat ? (
          <>
            <View style={styles.imageContainer}>
              {selectedHat.imageUrl ? (
                <Image
                  source={{ uri: selectedHat.imageUrl }}
                  style={styles.image}
                  resizeMode="cover"
                />
              ) : (
                <View style={styles.placeholderImage}>
                  <Text style={styles.placeholderText}>No image</Text>
                </View>
              )}
            </View>
            <Text style={styles.hatName}>{selectedHat.name}</Text>
          </>
        ) : (
          <>
            <View style={styles.placeholderImage}>
              <Text style={styles.placeholderText}>No hat selected</Text>
            </View>
            {hatsCount === 0 && (
              <Text style={styles.emptyMessage}>Add some hats to the collection</Text>
            )}
          </>
        )}
        
        <TouchableOpacity
          style={[styles.button, hatsCount === 0 && styles.buttonDisabled]}
          onPress={onSelect}
          disabled={hatsCount === 0}
        >
          <Text style={[styles.buttonText, hatsCount === 0 && styles.buttonTextDisabled]}>
            Pick a hat
          </Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 16,
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  imageContainer: {
    width: 200,
    height: 200,
    marginBottom: 16,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#f5f5f5',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  placeholderImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  placeholderText: {
    color: '#999',
    fontSize: 16,
  },
  hatName: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 24,
    textAlign: 'center',
  },
  emptyMessage: {
    textAlign: 'center',
    color: '#666',
    marginBottom: 24,
  },
  button: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 8,
  },
  buttonDisabled: {
    backgroundColor: '#ccc',
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  buttonTextDisabled: {
    color: '#999',
  },
});
